### PR TITLE
Formatting and linting

### PR DESCRIPTION
**Pull request by ian-r-rose**
This is perhaps a bit more controversial than my other PRs. I like having auto formatting and linting for projects that I work on. The former removes a whole lot of disagreements over minor things, and the latter can catch bugs before they ever make it to production.

This PR adds a pre-commit hook to the repository that checks formatting and linting, and applies `black` (c.f. #22 ) to staged changes.

You can set it up and try it by running
```
pip install pre-commit
pre-commit install
```
This will set up the repository (which will take a few minuets).

You can try it out by running, e.g.
```
pre-commit run black --all-files
```
Which will format the code. For normal usage, the hooks are invoked whenever you run `git commit`, an only on the files that have been changed.

If you are okay with this type of thing @vahedi25411, I can go through the process of fixing the lint errors, but I wanted to see what you think before reformatting the code base :)

### CODE REVIEW

**Comment by vahedi25411** [comment]
Generally speaking, I agree with everything that makes the development better. I have not used auto formatting and linting, so if you think they can improve the development process then why not.
But I need some time to get the hang of it.

**Comment by vahedi25411** [comment]
What do you mean by seeing it here?

**Comment by ian-r-rose** [comment]
I mean that I could do a pass with the linter and formatter and push the changes to this branch. But if you want to try it first, I can hold off.

**Comment by vahedi25411** [comment]
Ok, thank you for your clarification. I would be appreciated if you can hold off.

**Comment by ian-r-rose** [comment]
Any further thoughts on this? I have pushed another branch (`format-lint2`) that shows some of the changes, if you are curious.

**Comment by vahedi25411** [comment]
Actually I was working on a bug that took more time than I expected. 
I took a look at it but I didn't have time to play around with it. I think it is better for you to push your changes to this. 
Do you want me to merge?

**Comment by ian-r-rose** [comment]
Sure, happy to push the changes here. It would likely result in some merge-conflicts for work-in-progress branches, so I'm happy to deal with that in whatever way would be easier for you.

You would install the pre-commit hooks using `pre-commit install`, and then the first time you make a commit with them it will do some environment setup which will take a few minutes.

**Comment by vahedi25411** [comment]
Shall I delete the branch?

**Comment by ian-r-rose** [comment]
Just deleted. Thanks @vahedi25411 ! Let me know if you want to talk through usage of the pre-commit hooks, since they take a bit of time to get used to.

**Comment by vahedi25411** [comment]
Sure. I will get back to you after fixing the bug.

**Pull request merged**
