### PR TITLE
Line of interest and directions

### PR DESCRIPTION
**Pull request by vahedi25411**
#97

### CODE REVIEW

**Comment by vahedi25411** [comment]
@ian-r-rose  I fixed that issue but now there is another error and its message is not clear. Do you have any idea what is this error for?

**Comment by ian-r-rose** [comment]
I see every commit in this PR twice. How did this branch get a merge conflict with itself?

**Comment by ian-r-rose** [comment]
The failure is part of the check that the application works. It is checking if the CSV output matches the expected output. It looks like the time computation is off? The video is only two seconds long, but your CSV output seems to indicate that it is five minutes long.

**Comment by vahedi25411** [comment]
> I see every commit in this PR twice. How did this branch get a merge conflict with itself?

I don't have any idea. I just fixed the error and wanted to push the changes and I got the error that your commit is behind the head. So, I pulled and pushed again.

**Comment by vahedi25411** [comment]
> The failure is part of the check that the application works. It is checking if the CSV output matches the expected output. It looks like the time computation is off? The video is only two seconds long, but your CSV output seems to indicate that it is five minutes long.

So, I don't need to do anything. Right?

**Comment by ian-r-rose** [comment]
> 
> 
> > The failure is part of the check that the application works. It is checking if the CSV output matches the expected output. It looks like the time computation is off? The video is only two seconds long, but your CSV output seems to indicate that it is five minutes long.
> 
> So, I don't need to do anything. Right?

No, there is still a problem. It seems that the CSV output is calculating the time wrong.

**Comment by vahedi25411** [comment]
> > > The failure is part of the check that the application works. It is checking if the CSV output matches the expected output. It looks like the time computation is off? The video is only two seconds long, but your CSV output seems to indicate that it is five minutes long.
> > 
> > 
> > So, I don't need to do anything. Right?
> 
> No, there is still a problem. It seems that the CSV output is calculating the time wrong.

But I didn't change anything in calculating time.

**Comment by ian-r-rose** [comment]
I just tried it locally and was able to reproduce the problem, so something in this PR has definitely messed with the time calculation. CI is great!

**Pull request merged**
