### PR TITLE
Command line

### PR DESCRIPTION
**Pull request by vahedi25411**

### CODE REVIEW

**Comment by ian-r-rose** [comment]
Thanks @vahedi25411. There are some merge conflicts that need to be resolved.

I am still getting errors in envirionments where an x11 server doesn't exist. Seems there still an `imshow` somewhere.

**Comment by ian-r-rose** [comment]
I think this also has broken the GUI version. If I run `automated-walk-bike-counter --cli=false`, I get errors.

**Comment by vahedi25411** [comment]
@ian-r-rose  I fixed the conflicts.

**Comment by vahedi25411** [comment]
I also tried to run the GUI using `--cli=Flase` and it worked fine. Do you receive any error message or do you know what is causing the error for GUI?

**Comment by ian-r-rose** [comment]
The GUI seems to be working with the most recent commit. Now when I run
```
automated-walk-bike-counter --cli=true
```
I get an error because the file name is not specified:

```
Traceback (most recent call last):
  File "/home/ian/anaconda3/envs/automated-walk-bike-counter/bin/automated-walk-bike-counter", line 11, in <module>
    load_entry_point('automated-walk-bike-counter', 'console_scripts', 'automated-walk-bike-counter')()
  File "/mnt/c/Users/itacid457/repos/automated-walk-bike-counter/automated_walk_bike_counter/gui/app.py", line 140, in main
    cli.run()
  File "/mnt/c/Users/itacid457/repos/automated-walk-bike-counter/automated_walk_bike_counter/gui/app.py", line 128, in run
    tracker.trackObjects(config)
  File "/mnt/c/Users/itacid457/repos/automated-walk-bike-counter/automated_walk_bike_counter/core/tracking/object_tracker.py", line 351, in trackObjects
    m = re.match(r"([^\.]*)(\..*)", file)
  File "/home/ian/anaconda3/envs/automated-walk-bike-counter/lib/python3.7/re.py", line 173, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or bytes-like object
```
Can we add a more useful error message here?

This is also failing lint checks -- can you please run the pre-commit hooks?

**Comment by vahedi25411** [comment]
Sure. I will do. But for testing GUI you should use `--cli=Flase` ?

**Comment by vahedi25411** [comment]
@ian-r-rose  I ran `pre-commit`, is there anything I should do?

**Comment by ian-r-rose** [comment]
Yes, the GUI is working for me with the most recent commit.

In order to install the pre commit hooks you need to run `pre-commit install`. This will make it so that all subsequent commits are checked. However, in order to run it on the existing codebase, run `pre-commit run --all-files`.

**Comment by vahedi25411** [comment]
@ian-r-rose I ran `pre-commit run --all-files` and it fixed the pre-commit issues. But after that when I wanted to commit the changes I receive the following error:

`/usr/bin/env: ‘python’: No such file or directory`

Do you have any idea what is the issue?

**Comment by ian-r-rose** [comment]
I'm not sure -- are you in a conda environment? Are you sure that `pre-commit` is installed in the same environment that you are running in?

**Comment by vahedi25411** [comment]
For committing the changes I use git bash. But I installed the `pre-commit` on command prompt using pip on `anaconda`.

**Comment by ian-r-rose** [comment]
What python is available for in git bash? Is it not the one from the `conda` environment?

**Comment by vahedi25411** [comment]
I think I don't have python installed in git bash. I have python just installed on Conda environment. But why I had not received this error before running `pre-commit`.

**Comment by ian-r-rose** [comment]
I'm not sure, did you run it in the `conda` environment? You should be able to add `conda` to your path in git bash (I have that on my Windows machine).

**Comment by vahedi25411** [comment]
Yeah, you are right. Sorry for asking such a silly question.

**Comment by ian-r-rose** [comment]
Not silly! I think `pre-commit` is unfortunately a bit heavy and difficult to get set up, but I do like the ability to use it to automatically lint a codebase :/ 

On balance I like it, but it is definitely kind of annoying at times.

**Comment by ian-r-rose** [comment]
Any progress here? Note that if the git hooks are causing difficulty, you don't have to have them installed.

**Comment by vahedi25411** [comment]
Yes, I worked on this issue whole last weekend and I could fix the Python issue, then I got another error for Anaconda and I could fix it as well. After that, it was working fine but while I wanted to commit I was receiving another error that I could not find its solution.
Since I wanted to finish **exporting 15 minutes counter** I removed it in order to be able to push my changes but I will work on it later whenever I had time to work on its errors.

**Comment by ian-r-rose** [comment]
Thanks @vahedi25411, lint check is still failing.

**Comment by vahedi25411** [comment]
@ian-r-rose As I mentioned in my last comment I could not use `pre-commit` because it caused some error and I was not able to push my code.

Instead, I used `Black` to fix the formatting problem. If you have any suggestions to fix the issue I would be happy to know.

**Comment by ian-r-rose** [comment]
You can skip the git hooks by uninstalling them, or by running `git commit --no-verify`.

My suggestion for fixing the issue is to make sure that the right `python` and `pre-commit` executables are available in the PATH for the terminal in which you are running `git`. If that is not the case, I would expect problems like what you are seeing.

**Comment by ian-r-rose** [comment]
The `black` check is still failing in CI. I can push a tweak to fix it, but I'd also like to resolve this so we can be on the same page.

**Pull request merged**
