### PR TITLE
Gpu env

### PR DESCRIPTION
**Pull request by ian-r-rose**
This adds a gpu-flavored `environment.yml` which works on my ec2 box. @vahedi25411 when you get the chance can you see how well it works for you?

### CODE REVIEW

**Comment by ian-r-rose** [comment]
Ping @vahedi25411

**Comment by ian-r-rose** [comment]
@vahedi25411 did this environment work on your machine?

**Comment by vahedi25411** [comment]
No, because TensorFlow GPU should be installed on automated-walk-bike-counter environment.

**Comment by ian-r-rose** [comment]
This PR is all about adding a working tensorflow-gpu environment.

**Comment by ian-r-rose** [comment]
@vahedi25411 You would install this with `conda env create -f environment-gpu.yml`. You may need to delete the old environment before doing so.

**Comment by vahedi25411** [comment]
@ian-r-rose I installed the GPU version and it works fine.

**Pull request merged**
