### PR TITLE
Providing explanatory help text for configuration file

### LINKED ISSUE #79: Document thresholds and valid objects
The thresholds here
https://github.com/CityOfLosAngeles/automated-walk-bike-counter/blob/a4c95d7cc23ed48df6c9a286bc93dcf54f83e517/automated_walk_bike_counter/core/configuration.py#L32-L124
are do not have very well documented helpstrings, largely because I don't know what they do. @vahedi25411, can you add some more descriptive help strings to these configurables?

Likewise, I still don't fully understand the difference between `VALID_OBJECTS` and `search_objects`. Can you add some more text describing the difference? Should `VALID_OBJECTS` even be user-configurable, or should we remove it?

### PR DESCRIPTION
**Pull request by vahedi25411**
Fixes #79

### CODE REVIEW

**Comment by ian-r-rose** [comment]
Thanks @vahedi25411, looks like you were operating on an old version (before #74 and #81), so you are reverting a lot of the changes in those PRs. Can you start from the current `master` branch and add the help strings?

**Comment by ian-r-rose** [comment]
(In general you will run into a lot fewer conflicts if you always bull from `master` before starting on a PR)

**Comment by vahedi25411** [comment]
> Thanks @vahedi25411, looks like you were operating on an old version (before #74 and #81), so you are reverting a lot of the changes in those PRs. Can you start from the current `master` branch and add the help strings?

It is weird since I ran the `git pull origin master` on my branch and then I made my changes. Is there anything else I should do in order to get the `master` changes?

**Comment by ian-r-rose** [comment]
Probably worth starting fresh. You can say `git reset --hard origin/master` to get a fresh working copy.

**Comment by ian-r-rose** [comment]
Superseded by #87

**Pull request closed without merging**
